

export const PAYMENT_REQUEST="PAYMENT_REQUEST";
export const PAYMENT_SUCCESS="PAYMENT_SUCCESS";
export const PAYMENT_FAIL="PAYMENT_FAIL";


export const SINGLE_PAYMENT_REQUEST="SINGLE_PAYMENT_REQUEST";
export const SINGLE_PAYMENT_SUCCESS="SINGLE_PAYMENT_SUCCESS";
export const SINGLE_PAYMENT_FAIL="SINGLE_PAYMENT_FAIL";