export const AUTH_USER_REQUEST="AUTH_USER_REQUEST"
export const AUTH_USER_SUCCESS="AUTH_USER_SUCCESS"
export const AUTH_USER_FAIL="AUTH_USER_FAIL"
export const AUTH_USER_LOGOUT="AUTH_USER_LOGOUT"

export const ADD_USER_REQUEST="ADD_USER_REQUEST"
export const ADD_USER_SUCCESS="ADD_USER_SUCCESS"
export const ADD_USER_FAIL="ADD_USER_FAIL"

export const ALL_USER_REQUEST="ALL_USER_REQUEST"
export const ALL_USER_SUCCESS="ALL_USER_SUCCESS"
export const ALL_USER_FAIL="ALL_USER_FAIL"

export const UPDATE_USER_REQUEST="UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL="UPDATE_USER_FAIL"

export const SINGLE_USER_REQUEST="SINGLE_USER_REQUEST"
export const SINGLE_USER_SUCCESS="SINGLE_USER_SUCCESS"
export const SINGLE_USER_FAIL="SINGLE_USER_FAIL"